### PR TITLE
Align bounding box coordinates to detection model

### PR DESCRIPTION
**Pull request by tomer-algo**
# Intro
  - Align bounding box coordinates to detection model [y1, x1, y2, x2] (and not [x1, y1, x2, y2])
# Project
  - Suggested Skeleton
# Implemented Sections
  - Align bounding box coordinates with detection model
  - Use latest python_tools online package
  - small refactoring skeleton_handler.py
  - Did it require refactoring in other locations as well? No (Aligned to AI-Infra)
# Tests Description
  - Run inference in docker
# Undeveloped Sections
  - 
# What's New
  - 
# Checklist
  - [x] Module tested fully after last commit
  - [ ] Scheduled a PR meeting (if needed)
  - [ ] Documentation (comments or a dedicated documnet)
### Tested platforms
  - [x] Local
  - [ ] Cloud (Sagemaker)
  - [ ] Staging
  - [ ] Not relevant
### Tested Cameras
  - [ ] Gen 1.5
  - [ ] Gen 2
  - [ ] Not relevant
# Comments
### Included Features
  - 
### Infrastructure Dependencies
  - Align skeleton handler to Algo-Infra API
  https://docs.google.com/document/d/10xLk5DpcGo-Mu-P4KMHt_yt37Nvu187ghZRKyLlUUEs/edit?usp=sharing
  (PyTorch -> Skeleton)
### Tech Comments
  - update skeleton inference doc https://docs.google.com/document/d/18TOAEodIMwRWKnJIjXBFvGpwRB9Px_mYmV02ua245L4/edit?usp=sharing

### Testing Instructions
  - 
### Knowledge
| / | Link |
| ------ | ------ |
| Monday |  |
| TLD |  |
| Tech Spec | https://docs.google.com/document/d/1I-nFbP9ogt4qjc6rG6KAgeErb1NiQjf4Lk8LWF0O2-M/edit?usp=sharing |
### Todos
  - Run in ai-docs (after Amit's implementation)

### CODE REVIEW

**Review by Nimrods — CHANGES_REQUESTED** [review]
@tomer-algo 
You left the `.whl` files of the python package in the repo
Please remove it

**Comment by tomer-algo** [comment]
@Nimrods 
I've just updated to the new `.whl` file, the old one was already in the repo

**Comment by Nimrods** [comment]
@tomer-algo 
I don't think any of them should be in the repo - you can specify in a comment which version do we need
But I don't think it's a good idea to save the binary in the code repo

**Comment by tomer-algo** [comment]
@Nimrods 
Removed

**Review by Nimrods — APPROVED** [review]

**Pull request merged**
